### ISSUE TITLE
Error `command not found: _show_info`

### ISSUE THREAD

**Issue by Ved-un** [sheepla/fzpac#16] opened 2021-10-02 16:59 UTC
Doesn't work after update 
fzpac-git  r190.4f06f47-1

![2021-10-02_19-51](https://user-images.githubusercontent.com/48730277/135725708-1a410201-1c54-4c07-a1a9-2a04e94aa57a.png)

**Comment by sheepla** [comment] 2021-10-03 07:53
Thank you for your report. I tried `fzpac-git` on AUR `r190.4f06f47-1` but it didn't reproduce...

**Comment by soracqt** [comment] 2021-10-04 08:35
https://github.com/sheepla/fzpac/commit/f2f39fc07a1cd10bf79e5798d5031e6bc52d46a9
i think cause of this commit
![image](https://user-images.githubusercontent.com/72482919/135819402-3af2b966-53c0-4918-989a-5f9d2456d139.png)

**Comment by sheepla** [comment] 2021-10-04 09:51
Yes, I also think this commit is the cause. However, it could not be reproduced in my environment, so I will verify it.

**Comment by sheepla** [comment] 2021-10-04 09:54
It seems `export -f`  doesn't work

**Comment by soracqt** [comment] 2021-10-07 12:11
this bug affected zsh only

**Comment by sheepla** [comment] 2021-10-16 02:45
I will fix on `fix/16` branch.

**Comment by soracqt** [comment] 2021-10-16 03:40
in my environment,
 
```bash
SHELL=$(which zsh) fzpac l # error is displays
SHELL=$(which bash) fzpac l # no error is displays!! yay!!
```

**Comment by soracqt** [comment] 2021-10-16 11:25
❯ pacman -Q fzpac-git
fzpac-git r190.4f06f47-2
yes . install from aur

**Comment by sheepla** [comment] 2021-10-16 12:10
OK.  Reploduced with the same version of AUR! 🙆‍♂️: `fzpac-git r190.4f06f47-2` 

*MEMO*: The AUR gets the latest version of the `main` branch, so the modified commits haven't been merged yet.


@soracqt  Would you please try with the version modified by this commit? (on `fix/16` branch) I think the error will disappear.: 98b647d 

```bash
curl -O https://raw.githubusercontent.com/sheepla/fzpac/98b647d1109817d7b4fe14158245c3bd8a0f78f8/fzpac \
    && chmod +x fzpac
```

**Comment by soracqt** [comment] 2021-10-17 00:16
the error was gone! thanks

**Comment by sheepla** [comment] 2021-10-17 01:01
@soracqt Thanks so much for verifying!👍 I'll merge to `main` branch.

**Comment by sheepla** [comment] 2021-10-17 01:48
- [x] [v2.0.2](https://github.com/sheepla/fzpac/releases/tag/v2.0.2) released!

**Comment by sheepla** [comment] 2021-10-17 01:49
Thanks so much for your report and verification. Close this issue. ✅

**Closed by sheepla** 2021-10-17 01:49 UTC
Labels: bug, help wanted

**Comment by soracqt** [comment] 2021-10-17 03:34
i updated fzpac-git(aur)!
